"""
Figure A: Rule Impact Heatmap — Rank vs Percent Weekly Elimination Reversal Rate
=================================================================================
X-axis: Week index (1..T)
Y-axis: Season (1-34)
Color:  P(elimination outcome differs between Rank and Percent), blue(0%) to red(100%)
Marks:  star on known controversy events

Data source:
  task2_analysis.py generates season_{S}_weekly_diff.csv
  Columns: season, week, rule_A, rule_B, p_elim_diff
  Filter: rule_A='rank', rule_B='percent' (or vice versa)

Usage:
  Real data:  python fig_a_heatmap.py --data-dir /path/to/replay_results
  Demo mode:  python fig_a_heatmap.py --demo
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.colors as mcolors
import matplotlib.patheffects as patheffects
import argparse
import glob
import os


# ================================================================
# 1. Controversy event annotations
# ================================================================
CONTROVERSY_EVENTS = {
    # Jerry Rice S2 — finalist despite lowest judge scores in 5 weeks
    (2, 5): True, (2, 6): True, (2, 7): True,
    # Billy Ray Cyrus S4 — last place judge scores in 6 weeks
    (4, 3): True, (4, 4): True, (4, 5): True, (4, 6): True,
    # Bristol Palin S11 — lowest judge scores 12 times
    (11, 3): True, (11, 5): True, (11, 7): True, (11, 9): True,
    # Bobby Bones S27 — won despite consistently low judges
    (27, 4): True, (27, 6): True, (27, 8): True,
}

CONTROVERSY_SEASONS = {
    2:  'Jerry Rice (S2)',
    4:  'Billy Ray Cyrus (S4)',
    11: 'Bristol Palin (S11)',
    27: 'Bobby Bones (S27)',
}

RULE_SEGMENTS = {
    **{s: 'rank' for s in range(1, 3)},
    **{s: 'percent' for s in range(3, 28)},
    **{s: 'rank_save' for s in range(28, 35)},
}

RULE_COLORS = {
    'rank':      '#4A90D9',
    'percent':   '#F5A623',
    'rank_save': '#7B68EE',
}


# ================================================================
# 2. Data loading
# ================================================================
def load_real_data(data_dir):
    """Load from weekly_diff CSVs generated by task2_analysis.py."""
    all_rows = []
    pattern = os.path.join(data_dir, "season_*_weekly_diff.csv")
    files = glob.glob(pattern)

    if not files:
        raise FileNotFoundError(
            f"No season_*_weekly_diff.csv found in {data_dir}.\n"
            f"Run task2_replay.py --all and task2_analysis.py first,\n"
            f"or use --demo mode."
        )

    for fpath in sorted(files):
        all_rows.append(pd.read_csv(fpath))

    df_all = pd.concat(all_rows, ignore_index=True)

    mask = (
        ((df_all['rule_A'] == 'rank') & (df_all['rule_B'] == 'percent')) |
        ((df_all['rule_A'] == 'percent') & (df_all['rule_B'] == 'rank'))
    )
    df_rp = df_all[mask].copy()

    if df_rp.empty:
        raise ValueError("No rank-vs-percent comparison found.")

    return df_rp[['season', 'week', 'p_elim_diff']]


def generate_demo_data():
    """Generate synthetic demo data for 34 seasons."""
    np.random.seed(42)
    rows = []

    for season in range(1, 35):
        if season <= 6:
            n_weeks = np.random.randint(6, 9)
        elif season <= 20:
            n_weeks = np.random.randint(9, 12)
        else:
            n_weeks = np.random.randint(10, 13)

        rule = RULE_SEGMENTS.get(season, 'percent')

        for week in range(1, n_weeks + 1):
            if rule == 'rank':
                base_p = np.random.beta(2, 5)
            elif rule == 'percent':
                base_p = np.random.beta(2.5, 4)
            else:
                base_p = np.random.beta(3, 4)

            # Amplify for controversy seasons
            if season in CONTROVERSY_SEASONS:
                late_ratio = week / n_weeks
                if late_ratio > 0.4:
                    base_p = min(1.0, base_p + np.random.beta(3, 2) * 0.4)

            if (season, week) in CONTROVERSY_EVENTS:
                base_p = min(1.0, base_p + 0.25)

            rows.append({
                'season': season,
                'week': week,
                'p_elim_diff': np.clip(base_p, 0, 1)
            })

    return pd.DataFrame(rows)


# ================================================================
# 3. Matrix construction
# ================================================================
def build_heatmap_matrix(df):
    seasons = sorted(df['season'].unique())
    max_week = int(df['week'].max())

    matrix = np.full((len(seasons), max_week), np.nan)
    s2r = {s: i for i, s in enumerate(seasons)}

    for _, row in df.iterrows():
        matrix[s2r[int(row['season'])], int(row['week']) - 1] = row['p_elim_diff']

    return matrix, seasons, max_week


# ================================================================
# 4. Plot
# ================================================================
def plot_heatmap(matrix, seasons, max_week, is_demo=False, output_path=None):
    n_seasons = len(seasons)

    # --- Diverging colormap: Blue -> White -> Red ---
    cmap = mcolors.LinearSegmentedColormap.from_list(
        'reversal',
        ['#2166AC', '#67A9CF', '#D1E5F0', '#FDDBC7', '#EF8A62', '#B2182B'],
        N=256
    )
    cmap.set_bad(color='#F0F0F0')

    # --- Layout ---
    fig = plt.figure(figsize=(16, 11))
    gs = fig.add_gridspec(1, 4, width_ratios=[0.6, max_week, 3.2, 0.8], wspace=0.05)

    ax_rule = fig.add_subplot(gs[0, 0])
    ax_main = fig.add_subplot(gs[0, 1])
    ax_anno = fig.add_subplot(gs[0, 2])
    ax_cb   = fig.add_subplot(gs[0, 3])

    # ===== Main heatmap =====
    im = ax_main.imshow(
        matrix, aspect='auto', cmap=cmap, vmin=0, vmax=1,
        interpolation='nearest', origin='upper'
    )

    ax_main.set_xticks(range(max_week))
    ax_main.set_xticklabels(range(1, max_week + 1), fontsize=8)
    ax_main.set_xlabel('Week', fontsize=13, fontweight='bold', labelpad=8)

    ax_main.set_yticks(range(n_seasons))
    ax_main.set_yticklabels([f'S{s}' for s in seasons], fontsize=8)
    ax_main.set_ylabel('Season', fontsize=13, fontweight='bold', labelpad=8)

    # Star markers on controversy cells
    for (s, w) in CONTROVERSY_EVENTS:
        if s in seasons:
            row = seasons.index(s)
            col = w - 1
            if 0 <= col < max_week:
                ax_main.text(
                    col, row, '\u2605',  # ★
                    ha='center', va='center',
                    fontsize=9, color='white', fontweight='bold',
                    path_effects=[patheffects.withStroke(linewidth=2.5, foreground='black')]
                )

    # Minor grid
    ax_main.set_xticks(np.arange(-0.5, max_week, 1), minor=True)
    ax_main.set_yticks(np.arange(-0.5, n_seasons, 1), minor=True)
    ax_main.grid(which='minor', color='white', linewidth=0.3, alpha=0.5)
    ax_main.tick_params(which='minor', size=0)

    # ===== Left: Rule era strip =====
    ax_rule.set_xlim(0, 1)
    ax_rule.set_ylim(-0.5, n_seasons - 0.5)
    ax_rule.invert_yaxis()

    for i, s in enumerate(seasons):
        rule = RULE_SEGMENTS.get(s, 'percent')
        ax_rule.barh(i, 1, height=1, color=RULE_COLORS.get(rule, '#CCC'),
                     edgecolor='white', linewidth=0.5)

    ax_rule.set_yticks([])
    ax_rule.set_xticks([])
    ax_rule.set_xlabel('Rule\nEra', fontsize=10, fontweight='bold', labelpad=6)

    # ===== Right: Controversy annotations =====
    ax_anno.set_xlim(0, 1)
    ax_anno.set_ylim(-0.5, n_seasons - 0.5)
    ax_anno.invert_yaxis()
    ax_anno.axis('off')

    for s, name in CONTROVERSY_SEASONS.items():
        if s in seasons:
            row = seasons.index(s)
            ax_anno.annotate(
                f'  {name}',
                xy=(0.02, row), fontsize=9.5, fontweight='bold',
                color='#B2182B', va='center',
            )

    # ===== Colorbar =====
    cb = fig.colorbar(im, cax=ax_cb)
    cb.set_label('P(Elimination Differs | Rank vs Percent)',
                 fontsize=11, fontweight='bold', labelpad=12)
    cb.set_ticks([0, 0.25, 0.5, 0.75, 1.0])
    cb.set_ticklabels(['0%', '25%', '50%', '75%', '100%'])

    # ===== Title =====
    title = 'Figure A: Rule Impact Heatmap\nRank vs. Percent Weekly Elimination Reversal Rate'
    sub = 'Redder = higher posterior probability of different elimination outcomes'
    sub += '      \u2605 = known controversy event'
    if is_demo:
        sub += '      [DEMO DATA]'

    fig.suptitle(title, fontsize=14, fontweight='bold', y=0.98)
    ax_main.set_title(sub, fontsize=9.5, color='#555555', pad=14)

    # Rule legend
    patches = [
        mpatches.Patch(color=RULE_COLORS['rank'],      label='Rank (S1-S2)'),
        mpatches.Patch(color=RULE_COLORS['percent'],    label='Percent (S3-S27)'),
        mpatches.Patch(color=RULE_COLORS['rank_save'],  label="Rank + Judges' Save (S28-S34)"),
    ]
    fig.legend(handles=patches, loc='lower center', ncol=3, fontsize=10,
               frameon=True, edgecolor='#CCC', bbox_to_anchor=(0.45, 0.01))

    plt.subplots_adjust(top=0.89, bottom=0.09, left=0.06, right=0.95)

    # ===== Save =====
    base = str(output_path or 'fig_a_reversal_heatmap').replace('.png', '').replace('.pdf', '')
    fig.savefig(f'{base}.png', dpi=300, bbox_inches='tight', facecolor='white')
    fig.savefig(f'{base}.pdf', bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"Saved: {base}.png")
    print(f"Saved: {base}.pdf")
    return f'{base}.png', f'{base}.pdf'


# ================================================================
# 5. Summary statistics
# ================================================================
def print_summary(df):
    print("\n" + "=" * 65)
    print("REVERSAL RATE SUMMARY STATISTICS")
    print("=" * 65)

    overall = df['p_elim_diff'].mean()
    print(f"Overall mean reversal rate:  {overall:.1%}")

    by_s = df.groupby('season')['p_elim_diff'].mean()

    print(f"\nTop 5 seasons:")
    for s, v in by_s.nlargest(5).items():
        flag = '  <-- CONTROVERSY' if int(s) in CONTROVERSY_SEASONS else ''
        print(f"  S{int(s):2d} ({RULE_SEGMENTS.get(int(s),'?'):>10s}): {v:.1%}{flag}")

    print(f"\nBottom 5 seasons:")
    for s, v in by_s.nsmallest(5).items():
        print(f"  S{int(s):2d} ({RULE_SEGMENTS.get(int(s),'?'):>10s}): {v:.1%}")

    cs = set(CONTROVERSY_SEASONS.keys())
    mc = by_s[by_s.index.isin(cs)].mean()
    mo = by_s[~by_s.index.isin(cs)].mean()
    print(f"\nControversy seasons mean:     {mc:.1%}")
    print(f"Non-controversy seasons mean: {mo:.1%}")
    print(f"Difference:                   {mc - mo:+.1%}")

    print(f"\nBy rule era:")
    tmp = df.copy()
    tmp['rule_seg'] = tmp['season'].map(RULE_SEGMENTS)
    for rule, grp in tmp.groupby('rule_seg'):
        print(f"  {rule:>10s}: mean = {grp['p_elim_diff'].mean():.1%}")

    print("=" * 65)


# ================================================================
# 6. Entry point
# ================================================================
def main():
    parser = argparse.ArgumentParser(description='Figure A: Rule Impact Heatmap')
    parser.add_argument('--data-dir', type=str, default=None,
                        help='Directory with weekly_diff CSVs from task2_analysis.py')
    parser.add_argument('--demo', action='store_true',
                        help='Use synthetic demo data')
    parser.add_argument('--output', type=str, default=None,
                        help='Output file path (no extension)')
    args = parser.parse_args()

    if args.demo or args.data_dir is None:
        if not args.demo:
            print("WARNING: No --data-dir, using demo mode.\n")
        print("Generating demo heatmap...\n")
        df = generate_demo_data()
        is_demo = True
    else:
        print(f"Loading from {args.data_dir}...\n")
        df = load_real_data(args.data_dir)
        is_demo = False

    matrix, seasons, max_week = build_heatmap_matrix(df)
    print(f"Matrix: {len(seasons)} seasons x {max_week} weeks")
    print(f"Valid: {np.sum(~np.isnan(matrix))}, Missing: {np.sum(np.isnan(matrix))}")

    png, pdf = plot_heatmap(matrix, seasons, max_week, is_demo, args.output)
    print_summary(df)
    return png, pdf


if __name__ == '__main__':
    main()
